import { chromium } from 'playwright';
const [email, code] = process.argv.slice(2);
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const ctx = await b.newContext({ viewport: { width: 900, height: 900 } });
const p = await ctx.newPage();
await p.goto('http://localhost:3000/sign-in', { waitUntil: 'domcontentloaded' });
await p.fill('#email', email);
await p.getByRole('button', { name: /email me a sign-in link/i }).click();
await p.waitForTimeout(4000);
console.log('code box visible:', await p.locator('#code').count());
await p.screenshot({ path: '/tmp/shots/sign-in-sent.png', fullPage: true });
// A wrong code first, so the error path is exercised too.
await p.fill('#code', '00000000');
await p.getByRole('button', { name: /^sign in$/i }).click();
await p.waitForTimeout(2500);
console.log('wrong code says:', (await p.locator('[role=alert]').last().textContent().catch(()=>'—') || '').slice(0, 70));
await p.fill('#code', code);
await p.getByRole('button', { name: /^sign in$/i }).click();
await p.waitForTimeout(3500);
console.log('after correct code, url:', p.url());
await b.close();
